name: Changelog tester

on:
    workflow_dispatch:
        inputs:
            taggie:
                description: 'Publish release branch'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "14.x"

            - name: Git log
              run: |
                  git log `${{ github.event.inputs.taggie }}`..HEAD --oneline

            - name: Run test
              run: node index
