name: Changelog tester

on:
    workflow_dispatch:
        inputs:
            taggie:
                description: 'Publish release branch'
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                ref: master

            - name: Git log
              run: |
                git log `git tag --sort=creatordate | /usr/bin/tail -1`..HEAD --pretty=format:'%s - %an'

            - name: Get this branch name
              id: extract_branch
              run: echo ::set-output name=BRANCH_NAME::$(git branch --show-current)

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "14.x"

            - name: Run test
              env:
                  test: Hello
              run: node index
